version: '3.0'

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    enviroment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_USER=docker
      - POSTGRES_DB=shortlinks

  redis:
    image: bitnami/redis:latest
    ports:
    - "6379:6379"
    enviroments:
    - REDIS_PASSWORD=docker
